### PR TITLE
Bookmark CFIs using Ranges instead of Spatial offset (WIP) #157

### PR DESCRIPTION
**Pull request by JCCR**
See #157

### Notes:
- How well does this work with RTL/VWM?
- CFI library sync up

~~Some irrelevant (potentially useful) changes sneaked in:~~
~~- Attempt at preventing image overrun, now takes into account of padding/margin..~~
~~https://github.com/readium/readium-shared-js/pull/158/files#diff-5899c9a9fc900e9651da6e2d81f3025bR778~~
~~- Reduce extraneous pagination events that occur under certain conditions..~~

### CODE REVIEW

**Comment by JCCR** [comment]
@danielweck

**Comment by danielweck** [comment]
I look forward to giving this a try Juan.
Eventually, would it be possible to extract the onPaginationChanged fixes into a separate Pull Request? I think we would need to track potential regression bugs separately for this (e.g. Media Overlays page turn sync engine)

**Comment by JCCR** [comment]
@danielweck I have removed the separate fixes from this PR.
I also reviewed the CFI library usage and have determined that this is compatible with everything in 'develop' on the cfi library repo. So I will update the CFI library in this branch with a build from there.

**Comment by danielweck** [comment]
Thanks @JCCR much appreciated. Sorry I don't have time to look into the details right away.
PS: updating the pre-built CFI lib sounds like a good idea, and this feature branch / Pull Request is a good place to do it.

**Comment by JCCR** [comment]
@danielweck Yea, it's ok if you can't right now. I found a bug with my CFI library update anyway :)

**Comment by JCCR** [comment]
@danielweck Cleaned up some code a bit, and fixed code missing in the CFI library for some of this.

**Comment by JCCR** [comment]
Closed in favour of #210

**Pull request closed without merging**
