### PR TITLE
Rdh stop propagation on handled trigger

### PR DESCRIPTION
**Pull request by kimtuck**
#### Related issue(s) and/or pull request(s)
No related issue.

### Additional information
Bibliotheca's hybrid app has a click handler attached to the body tag of the iframe.  If the user clicks the left or right portion of the page, we move to the previous/next page; if they click in the center, we open a menu.

If there is a clickable element on the page that is configured using a <epub:trigger tag, when that element is clicked, the handler is executed.  But the readium code allows the event to bubble, so that our event handler also sees the click and responds.

There is no need for our event handler to fire, since the event was already handled by the code in the epub.

### CODE REVIEW

**Comment by danielweck** [comment]
Thanks! Let's get this merged.
There is currently a conflict with the readium-cfi-js submodule. Could you please update it to the latest revision as per the develop branch?

**Comment by kimtuck** [comment]
Do you have any advice on how to do that?  I don’t normally work with repos that have submodules.  Thanks.

**Comment by danielweck** [comment]
Command line from folder `readium-shared-js` in your fork:
`cd readium-cfi-js && git checkout develop && git pull && ls && cd .. && git commit readium-cfi-js -m "updated submodule"`

**Comment by danielweck** [comment]
Merged :)

**Comment by kimtuck** [comment]
Hi Daniel,

Thanks for you help with the submodule issue, very helpful.

Hoping you can be helpful again ☺

I have a couple of pull requests I want to make for readium-js; and I’m seeing the same thing – the readium-cfi-js issue.

I started out by forking the readium-js repo into my github account; then cloning that to my computer; making branches and checking in my changes.

Now I’m ready to do pull requests, but I’m seeing the same thing with the readium-cfi-js.

So I updated the submodules for readium-js; that gives me the readium-shared-js; and I went into there and update the submodules for readium-cfi-js.

When I push to my fork for readium-js; it didn’t fix the issue in the pull request page – the readium-cfi-js still shows a difference.
I can’t push the readium-shared-js; because that points to the readium repo, not my fork.

Any ideas?

**Comment by danielweck** [comment]
Good point. I imagine that your Git fork is configured with different (non-readium) submodule remotes. Damn! :(
(one of the reasons why some of us would like to stop using submodules)

**Comment by rkwright** [comment]
@danielweck :  Is there anyone who DOESN'T want to get rid of those @#$^! submodules.  One of my main wishlist items for Readium-2.  
@kimtuck :  Have you been following, have interest in or care about Readium-2?

**Comment by kimtuck** [comment]
No, at this point in time, I don’t know anything about readium2.  Can you point me to it?  Thanks.

**Comment by llemeurfr** [comment]
Readium-2 is currently in a "brainstorming" phase, you can find info about how to follow the work in 
https://github.com/readium/readium-2/wiki/Documents-and-communication <https://github.com/readium/readium-2/wiki/Documents-and-communication>

you can follow the threads in 
https://github.com/readium/readium-2/issues <https://github.com/readium/readium-2/issues>

We are now focusing on the EPUB 3 "fetcher-parser-streamer" base module, on which rendering modules will be built later. 

Happy if you can join the discussion.

Laurent Le Meur
CTO, EDRLab

laurent.lemeur@edrlab.org <mailto:laurent.lemeur@edrlab.org>
Tel: +33 (0)1.40.41.11.89

**Pull request merged**
